import type { AnalysisReport, RecoveryCandidate } from "./model.js";

export function renderMarkdown(report: AnalysisReport): string {
  const classCandidates = report.candidates.filter((candidate) => isTypeCandidate(candidate));
  const methodCandidates = report.candidates.filter((candidate) => !isTypeCandidate(candidate));
  const lines = [
    "# Apex recovery analysis",
    "",
    `Generated by apex-reach ${report.tool.version} at ${report.generatedAt}.`,
    "",
    "> This is deterministic offline evidence, not a safe-to-delete verdict. Validate org-only metadata, scheduled/queued work, configuration-driven dispatch, and external consumers before changing code.",
    "",
    "## Executive summary",
    "",
    `- ${formatNumber(report.inventory.apexFiles)} Apex files and ${formatNumber(report.summary.symbols)} symbols analyzed.`,
    `- ${formatNumber(report.inventory.productionApexCharacters)} raw production source characters (${formatBytes(report.inventory.productionApexBytes)}).`,
    `- ${formatNumber(report.inventory.testApexCharacters)} raw test source characters, reported separately because @isTest code does not consume the org Apex code limit.`,
    `- ${formatNumber(report.summary.productionReachable)} symbols reachable from production entry points.`,
    `- ${formatNumber(report.summary.testOnlyReachable)} symbols reached only from tests.`,
    `- ${formatNumber(report.summary.candidateClasses)} top-level recovery candidate types representing up to ${formatNumber(report.summary.candidateClassCharacters)} raw characters (${formatBytes(report.summary.candidateClassBytes)}).`,
    `- ${formatNumber(report.summary.candidateMethods)} method or constructor candidates for class-level refactoring.`,
    "",
    "Raw source size includes comments and is an offline estimate. Tooling API `LengthWithoutComments` should be used when exact deployed-org attribution is available.",
    "",
    "## Top-level recovery candidates",
    "",
    ...renderCandidateTable(classCandidates),
    "",
    "## Method and constructor candidates",
    "",
    ...renderCandidateTable(methodCandidates, 100),
    "",
    "## Analysis coverage",
    "",
    `- ${formatNumber(report.summary.entryPoints)} platform, annotation, metadata, and test entry points.`,
    `- ${formatNumber(report.summary.resolvedReferences)} resolved reference edges.`,
    `- ${formatNumber(report.summary.unresolvedReferences)} unresolved reference observations.`,
    `- ${formatNumber(report.diagnostics.length)} Apex parse diagnostics.`,
    "- Production and test reachability are computed separately; JSON contains a symbol-by-symbol evidence path.",
    "",
    "## Uncertainty signals",
    "",
    ...renderUncertainties(report),
    "",
    "## Recommended review order",
    "",
    "1. Inspect high-confidence top-level candidates, largest first.",
    "2. Confirm no org-only Flow, Visualforce, Aura, scheduled job, custom metadata, managed-package, SOAP/REST, or external integration references them.",
    "3. Use method candidates to reduce live classes; deploy the modified class before expecting Apex capacity to change.",
    "4. Re-run the analyzer and the full Salesforce test suite after each removal batch.",
    "",
  ];
  return lines.join("\n");
}

function renderCandidateTable(candidates: RecoveryCandidate[], limit = 50): string[] {
  if (candidates.length === 0) return ["No candidates in this category."];
  const rows = [
    "| Confidence | Symbol | Kind | Raw chars | Raw size | Location | Uncertainty |",
    "|---|---|---:|---:|---:|---|---|",
  ];
  for (const candidate of candidates.slice(0, limit)) {
    rows.push(`| ${candidate.confidence} | \`${escapeCell(candidate.qualifiedName)}\` | ${candidate.kind} | ${formatNumber(candidate.sourceCharacters)} | ${formatBytes(candidate.sourceBytes)} | \`${candidate.location.path}:${candidate.location.line}\` | ${escapeCell(candidate.uncertainties.join(" ") || "None observed")} |`);
  }
  if (candidates.length > limit) rows.push(`\n_${formatNumber(candidates.length - limit)} additional candidates are available in the JSON report._`);
  return rows;
}

function renderUncertainties(report: AnalysisReport): string[] {
  const grouped = new Map<string, number>();
  for (const uncertainty of report.uncertainties) grouped.set(uncertainty.code, (grouped.get(uncertainty.code) ?? 0) + 1);
  if (grouped.size === 0) return ["No uncertainty signals were observed."];
  return [...grouped.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([code, count]) => `- \`${code}\`: ${formatNumber(count)}`);
}

function isTypeCandidate(candidate: RecoveryCandidate): boolean {
  return candidate.kind === "class" || candidate.kind === "interface" || candidate.kind === "enum";
}

function formatNumber(value: number): string {
  return new Intl.NumberFormat("en-US").format(value);
}

function formatBytes(value: number): string {
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KiB`;
  return `${(value / (1024 * 1024)).toFixed(2)} MiB`;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}
