import type { AnalysisReport, RecoveryCandidate } from "./model.js";

export function renderMarkdown(report: AnalysisReport): string {
  const classCandidates = report.candidates.filter((candidate) => isTypeCandidate(candidate));
  const methodCandidates = report.candidates.filter((candidate) => !isTypeCandidate(candidate));
  const lines = [
    "# Apex recovery analysis",
    "",
    `Generated by apex-reach ${report.tool.version} at ${report.generatedAt}.`,
    "",
    "> This is a deterministic closed-world repository result: all deployable Apex and calling metadata are assumed to be present in the analyzed SFDX package directories. Callers outside the repository are outside the result by definition.",
    "",
    "## Leadership view",
    "",
    `- **Repository-unreachable code:** **${formatPercent(report.executive.deprecationCandidatePercent)}** of production Apex has no path from a production code or metadata entry point (${formatNumber(report.executive.deprecationCandidateCharacters)} raw characters).`,
    `- **Repository-reachable code:** **${formatPercent(report.executive.retainedPercent)}** has a production path in the analyzed repository.`,
    `- **Candidate actions:** ${formatNumber(report.executive.topLevelCandidateFiles)} top-level files for deprecation review and ${formatNumber(report.executive.internalRefactorCandidates)} internal methods/constructors for refactoring review.`,
    `- **Conclusion status:** ${report.analysis.status === "complete" ? "complete — no blocking analysis gaps were found" : `blocked — ${formatNumber(report.analysis.blockers.filter((blocker) => blocker.blocksClosedWorldConclusion).length)} analysis gap(s) must be resolved`}.`,
    "- **Redundant code:** not measured in this version. No duplication percentage is inferred until token-based clone analysis is available.",
    "",
    "Candidate classification is binary, not probabilistic. Exposure flags describe how code could be invoked; they do not change whether a repository call was found.",
    "",
    "## Technical summary",
    "",
    `- ${formatNumber(report.inventory.apexFiles)} Apex files and ${formatNumber(report.summary.symbols)} symbols analyzed.`,
    `- ${formatNumber(report.inventory.productionApexCharacters)} raw production source characters (${formatBytes(report.inventory.productionApexBytes)}).`,
    `- ${formatNumber(report.inventory.testApexCharacters)} raw test source characters, reported separately because @isTest code does not consume the org Apex code limit.`,
    `- ${formatNumber(report.summary.productionReachable)} symbols reachable from production entry points.`,
    `- ${formatNumber(report.summary.testOnlyReachable)} symbols reached only from tests.`,
    `- ${formatNumber(report.summary.candidateClasses)} top-level repository-unreachable types representing ${formatNumber(report.summary.candidateClassCharacters)} raw characters (${formatBytes(report.summary.candidateClassBytes)}).`,
    `- ${formatNumber(report.summary.candidateMethods)} method or constructor candidates for class-level refactoring.`,
    "",
    "Raw source size includes comments and is an offline estimate. Tooling API `LengthWithoutComments` should be used when exact deployed-org attribution is available.",
    "",
    "## Top-level recovery candidates",
    "",
    ...renderCandidateTable(classCandidates),
    "",
    "## Method and constructor candidates",
    "",
    ...renderCandidateTable(methodCandidates, 100),
    "",
    "## Analysis coverage",
    "",
    `- ${formatNumber(report.inventory.metadataFiles)} text metadata files scanned across the SFDX package directories.`,
    `- ${formatNumber(report.summary.entryPoints)} concrete trigger, metadata, and test entry points.`,
    `- ${formatNumber(report.summary.resolvedReferences)} resolved reference edges.`,
    `- ${formatNumber(report.summary.unresolvedReferences)} unresolved reference observations.`,
    `- ${formatNumber(report.diagnostics.length)} Apex parse diagnostics.`,
    "- Production and test reachability are computed separately; JSON contains a symbol-by-symbol evidence path.",
    "",
    "## Analysis blockers",
    "",
    ...renderBlockers(report),
    "",
    "## Recommended review order",
    "",
    "1. Resolve every blocking analysis gap; each item includes an exact repository location.",
    "2. Inspect the largest repository-unreachable top-level candidates first. Exposure is shown separately and is not a probability.",
    "3. Use method candidates to reduce live classes; deploy the modified class before expecting Apex capacity to change.",
    "4. Re-run the analyzer and the full Salesforce test suite after each removal batch.",
    "",
  ];
  return lines.join("\n");
}

function renderCandidateTable(candidates: RecoveryCandidate[], limit = 50): string[] {
  if (candidates.length === 0) return ["No candidates in this category."];
  const rows = [
    "| Classification | Symbol | Kind | Raw chars | Raw size | Location | Exposure flags |",
    "|---|---|---:|---:|---:|---|---|",
  ];
  for (const candidate of candidates.slice(0, limit)) {
    rows.push(`| unreachable in repository | \`${escapeCell(candidate.qualifiedName)}\` | ${candidate.kind} | ${formatNumber(candidate.sourceCharacters)} | ${formatBytes(candidate.sourceBytes)} | \`${candidate.location.path}:${candidate.location.line}\` | ${escapeCell(candidate.exposures.join(" ") || "None")} |`);
  }
  if (candidates.length > limit) rows.push(`\n_${formatNumber(candidates.length - limit)} additional candidates are available in the JSON report._`);
  return rows;
}

function renderBlockers(report: AnalysisReport): string[] {
  if (report.analysis.blockers.length === 0) return ["No analysis blockers were found. The closed-world repository conclusion is complete."];
  const rows = [
    "| Blocking | Code | Location | Detail |",
    "|---|---|---|---|",
  ];
  for (const blocker of report.analysis.blockers) {
    const location = blocker.location ? `\`${blocker.location.path}:${blocker.location.line}\`` : "Project";
    rows.push(`| ${blocker.blocksClosedWorldConclusion ? "yes" : "no (conservative resolution)"} | \`${blocker.code}\` | ${location} | ${escapeCell(blocker.message)} |`);
  }
  return rows;
}

function isTypeCandidate(candidate: RecoveryCandidate): boolean {
  return candidate.kind === "class" || candidate.kind === "interface" || candidate.kind === "enum";
}

function formatNumber(value: number): string {
  return new Intl.NumberFormat("en-US").format(value);
}

function formatPercent(value: number): string {
  return `${value.toFixed(2)}%`;
}

function formatBytes(value: number): string {
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KiB`;
  return `${(value / (1024 * 1024)).toFixed(2)} MiB`;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}
